import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';
import { NavbarSimple } from '@/components/Navbar/NavbarSimple';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          {/* Pembungkus Flexbox agar Navbar & Konten bersebelahan */}
          <div style={{ display: 'flex' }}>
            
            {/* Kolom Kiri: Navbar (lebarnya akan mengikuti isi navbar) */}
            <NavbarSimple />

            {/* Kolom Kanan: Isi Konten (mengambil sisa ruang yang ada) */}
            <main style={{ flex: 1, padding: '20px', minHeight: '100vh' }}>
              {children}
            </main>

          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
